version: '3'
services:
  jenkins-master.openlogic.local:
    build: jenkins-master
    image: jenkins-master:2.46.1-alpine
    container_name: Jenkins-Master
    restart: always
    ports:
      - "51206:50000"
    volumes:
      - ./jenkins-master/volume_data/logs:/var/log/jenkins
      - ./jenkins-master/volume_data/home:/var/jenkins_home
    depends_on:
      - jenkins-nginx.openlogic.local
  jenkins-nginx.openlogic.local:
    build: jenkins-nginx
    image: jenkins-nginx:1.11.12-alpine
    container_name: Jenkins-NGINX
    restart: always
    ports:
      - "51205:443"
    volumes:
      - ./jenkins-nginx/volume_data/ssl:/etc/ssl/certs/nginx:ro
  jenkins-slave.openlogic.local:
    build: jenkins-slave
    image: jenkins-slave:8u121-jdk-alpine
    container_name: Jenkins-Slave
    depends_on:
      - jenkins-master.openlogic.local
#    volumes:
#      - ./jenkins-slave/volume_data/ssl:/etc/ssl/java/truststore:ro
networks:
  default:
    external:
      name: development
